package com.eldanior.system.config.enums;

public enum MobXP {
    // === BOSS & EVENTS ===
    DRAGON_FIRE("dragon fire", 10000),
    DRAGON_FROST("dragon frost", 10000),
    SHADOW_KNIGHT("shadow knight", 2000),
    GOBLIN_DUKE_PHASE_2("goblin duke phase 2", 1750),
    GOBLIN_DUKE_PHASE_3_FAST("goblin duke phase 3 fast", 1600),
    GOBLIN_DUKE_PHASE_3_SLOW("goblin duke phase 3 slow", 1600),
    GOBLIN_DUKE("goblin duke", 1500),
    WHALE_HUMPBACK("whale humpback", 1500),
    YETI("yeti", 1650),
    REX_CAVE("rex cave", 1450),
    WEREWOLF("werewolf", 1300),
    GOLEM_GUARDIAN_VOID("golem guardian void", 1400),
    DUNGEON_SCARAK_BROODMOTHER("dungeon scarak broodmother", 1500),
    DUNGEON_SCARAK_BROODMOTHER_YOUNG("dungeon scarak broodmother young", 1250),

    // === SKELETONS & UNDEAD ===
    SKELETON_INCANDESCENT_FOOTMAN("skeleton incandescent footman", 80),
    SKELETON_INCANDESCENT_FIGHTER("skeleton incandescent fighter", 80),
    SKELETON_INCANDESCENT_MAGE("skeleton incandescent mage", 80),
    SKELETON_INCANDESCENT_HEAD("skeleton incandescent head", 50),
    SKELETON_BURNT_PRAETORIAN("skeleton burnt praetorian", 150),
    SKELETON_BURNT_ALCHEMIST("skeleton burnt alchemist", 70),
    SKELETON_BURNT_SOLDIER("skeleton burnt soldier", 60),
    SKELETON_BURNT_KNIGHT("skeleton burnt knight", 60),
    SKELETON_BURNT_LANCER("skeleton burnt lancer", 60),
    SKELETON_BURNT_GUNNER("skeleton burnt gunner", 50),
    SKELETON_BURNT_WIZARD("skeleton burnt wizard", 50),
    SKELETON_BURNT_ARCHER("skeleton burnt archer", 40),
    SKELETON_FROST_ARCHMAGE("skeleton frost archmage", 70),
    SKELETON_FROST_SOLDIER("skeleton frost soldier", 50),
    SKELETON_FROST_FIGHTER("skeleton frost fighter", 50),
    SKELETON_FROST_KNIGHT("skeleton frost knight", 50),
    SKELETON_FROST_RANGER("skeleton frost ranger", 40),
    SKELETON_FROST_ARCHER("skeleton frost archer", 40),
    SKELETON_FROST_MAGE("skeleton frost mage", 40),
    SKELETON_FROST_SCOUT("skeleton frost scout", 30),
    SKELETON_SAND_SOLDIER("skeleton sand soldier", 40),
    SKELETON_SAND_ARCHMAGE("skeleton sand archmage", 40),
    SKELETON_SAND_ASSASSIN("skeleton sand assassin", 40),
    SKELETON_SAND_ARCHER("skeleton sand archer", 30),
    SKELETON_SAND_GUARD("skeleton sand guard", 30),
    SKELETON_SAND_MAGE("skeleton sand mage", 30),
    SKELETON_SAND_RANGER("skeleton sand ranger", 25),
    SKELETON_SAND_SCOUT("skeleton sand scout", 25),
    SKELETON_PIRATE_STRIKER("skeleton pirate striker", 60),
    SKELETON_PIRATE_CAPTAIN("skeleton pirate captain", 50),
    SKELETON_PIRATE_GUNNER("skeleton pirate gunner", 40),
    SKELETON_ARCHMAGE("skeleton archmage", 60),
    SKELETON_SOLDIER("skeleton soldier", 40),
    SKELETON_KNIGHT("skeleton knight", 40),
    SKELETON_RANGER("skeleton ranger", 35),
    SKELETON_MAGE("skeleton mage", 35),
    SKELETON_SCOUT("skeleton scout", 30),
    SKELETON_ARCHER("skeleton archer", 25),
    SKELETON_FIGHTER("skeleton fighter", 25),
    SKELETON_BASE("skeleton", 20),
    DUNGEON_SKELETON_SAND_SOLDIER("dungeon skeleton sand soldier", 45),
    DUNGEON_SKELETON_SAND_ARCHER("dungeon skeleton sand archer", 45),
    DUNGEON_SKELETON_SAND_ASSASSIN("dungeon skeleton sand assassin", 45),
    DUNGEON_SKELETON_SAND_MAGE("dungeon skeleton sand mage", 45),
    ZOMBIE_ABERRANT_BIG("zombie aberrant big", 200),
    ZOMBIE_ABERRANT_SMALL("zombie aberrant small", 80),
    ZOMBIE_ABERRANT("zombie aberrant", 250),
    ZOMBIE_BURNT("zombie burnt", 50),
    ZOMBIE_FROST("zombie frost", 40),
    ZOMBIE_SAND("zombie sand", 30),
    ZOMBIE_BASE("zombie", 25),
    GHOUL("ghoul", 100),
    WRAITH_LANTERN("wraith lantern", 50),
    WRAITH("wraith", 100),
    HOUND_BLEACHED("hound bleached", 60),
    HORSE_SKELETON_ARMORED("horse skeleton armored", 120),
    HORSE_SKELETON("horse skeleton", 90),
    PIG_UNDEAD("pig undead", 40),
    COW_UNDEAD("cow undead", 50),
    CHICKEN_UNDEAD("chicken undead", 20),

    // === TRORKS ===
    TRORK_DOCTOR_WITCH("trork doctor witch", 60),
    TRORK_CHIEFTAIN("trork chieftain", 100),
    TRORK_WARRIOR("trork warrior", 40),
    TRORK_SHAMAN("trork shaman", 45),
    TRORK_BRAWLER("trork brawler", 40),
    TRORK_HUNTER("trork hunter", 40),
    TRORK_GUARD("trork guard", 40),
    TRORK_MAULER("trork mauler", 40),
    TRORK_SENTRY("trork sentry", 40),
    TRORK_UNARMED("trork unarmed", 20),

    // === OUTLANDERS ===
    OUTLANDER_BERSERKER("outlander berserker", 70),
    OUTLANDER_MARAUDER("outlander marauder", 60),
    OUTLANDER_PRIEST("outlander priest", 65),
    OUTLANDER_SORCERER("outlander sorcerer", 65),
    OUTLANDER_BRUTE("outlander brute", 80),
    OUTLANDER_CULTIST("outlander cultist", 50),
    OUTLANDER_HUNTER("outlander hunter", 40),
    OUTLANDER_STALKER("outlander stalker", 40),
    OUTLANDER_PEON("outlander peon", 30),

    // === SCARAKS ===
    SCARAK_FIGHTER_ROYAL_GUARD("scarak fighter royal guard", 70),
    SCARAK_BROODMOTHER("scarak broodmother", 120),
    SCARAK_DEFENDER("scarak defender", 60),
    SCARAK_FIGHTER("scarak fighter", 45),
    SCARAK_SEEKER("scarak seeker", 35),
    SCARAK_LOUSE("scarak louse", 10),
    DUNGEON_SCARAK_DEFENDER("dungeon scarak defender", 65),
    DUNGEON_SCARAK_FIGHTER("dungeon scarak fighter", 50),
    DUNGEON_SCARAK_SEEKER("dungeon scarak seeker", 40),
    DUNGEON_SCARAK_LOUSE("dungeon scarak louse", 15),

    // === GOBLINS ===
    GOBLIN_OGRE("goblin ogre", 100),
    GOBLIN_SCAVENGER_BATTLEAXE("goblin scavenger battleaxe", 40),
    GOBLIN_SCAVENGER_SWORD("goblin scavenger sword", 40),
    GOBLIN_SCAVENGER("goblin scavenger", 35),
    GOBLIN_LOBBER("goblin lobber", 35),
    GOBLIN_SCRAPPER("goblin scrapper", 30),
    GOBLIN_MINER("goblin miner", 30),
    GOBLIN_HERMIT("goblin hermit", 30),
    GOBLIN_THIEF("goblin thief", 35),

    // === ELEMENTALS & GOLEMS ===
    GOLEM_CRYSTAL_EARTH("golem crystal earth", 150),
    GOLEM_CRYSTAL_FLAME("golem crystal flame", 200),
    GOLEM_CRYSTAL_FROST("golem crystal frost", 180),
    GOLEM_CRYSTAL_SAND("golem crystal sand", 160),
    GOLEM_CRYSTAL_THUNDER("golem crystal thunder", 160),
    GOLEM_FIRESTEEL("golem firesteel", 180),
    SPIRIT_THUNDER("spirit thunder", 100),
    SPIRIT_EMBER("spirit ember", 80),
    SPIRIT_FROST("spirit frost", 60),
    SPIRIT_ROOT("spirit root", 40),

    // === BEASTS & PREDATORS ===
    EMBERWULF("emberwulf", 120),
    TIGER_SABERTOOTH("tiger sabertooth", 100),
    BEAR_GRIZZLY("bear grizzly", 100),
    BEAR_POLAR("bear polar", 90),
    MOOSE_BULL("moose bull", 100),
    MOOSE_COW("moose cow", 80),
    TOAD_RHINO_MAGMA("toad rhino magma", 100),
    TOAD_RHINO("toad rhino", 90),
    MOSSHORN_PLAIN("mosshorn plain", 100),
    MOSSHORN("mosshorn", 90),
    WOLF_OUTLANDER_SORCERER("wolf outlander sorcerer", 80),
    WOLF_OUTLANDER_PRIEST("wolf outlander priest", 80),
    WOLF_TRORK_SHAMAN("wolf trork shaman", 70),
    WOLF_TRORK_HUNTER("wolf trork hunter", 40),
    WOLF_BLACK("wolf black", 60),
    WOLF_WHITE("wolf white", 60),
    FEN_STALKER("fen stalker", 60),
    LEOPARD_SNOW("leopard snow", 80),
    LIZARD_SAND("lizard sand", 60),
    SCORPION("scorpion", 80),
    CROCODILE("crocodile", 110),
    RAPTOR_CAVE("raptor cave", 80),
    SPIDER_CAVE("spider cave", 50),
    SPIDER_BASE("spider", 40),
    SNAKE_COBRA("snake cobra", 50),
    SNAKE_RATTLE("snake rattle", 40),
    SNAKE_MARSH("snake marsh", 30),
    HYENA("hyena", 50),
    FOX("fox", 20),
    RAT("rat", 10),
    MOLERAT("molerat", 30),
    SLUG_MAGMA("slug magma", 50),
    SNAIL_MAGMA("snail magma", 40),
    SNAIL_FROST("snail frost", 40),
    SNAPDRAGON("snapdragon", 60),
    CACTEE("cactee", 30),
    BRAMBLEKIN_SHAMAN("bramblekin shaman", 60),
    BRAMBLEKIN("bramblekin", 50),

    // === VOID ===
    SPAWN_VOID("spawn void", 150),
    SPECTRE_VOID("spectre void", 80),
    CRAWLER_VOID("crawler void", 60),
    EYE_VOID("eye void", 50),
    LARVA_VOID("larva void", 20),

    // === INTELLIGENT & FACTIONS ===
    FERAN_WINDWALKER("feran windwalker", 50),
    FERAN_SHARPTOOTH("feran sharptooth", 50),
    FERAN_LONGTOOTH("feran longtooth", 50),
    FERAN_BURROWER("feran burrower", 45),
    FERAN_CIVILIAN("feran civilian", 35),
    FERAN_CUB("feran cub", 15),
    KWEEBEC_RAZORLEAF("kweebec razorleaf", 60),
    KWEEBEC_SAPLING_ORANGE("kweebec sapling orange", 35),
    KWEEBEC_SAPLING_PINK("kweebec sapling pink", 35),
    KWEEBEC_SAPLING("kweebec sapling", 40),
    KWEEBEC_ROOTLING("kweebec rootling", 35),
    KWEEBEC_SPROUTLING("kweebec sproutling", 25),
    KWEEBEC_SEEDLING("kweebec seedling", 15),
    KWEEBEC_PRISONER("kweebec prisoner", 30),
    KWEEBEC_ELDER("kweebec elder", 30),
    SLOTHIAN("slothian", 120),
    TULUK_FISHERMAN("tuluk fisherman", 80),
    KLOPS_GENTLEMAN("klops gentleman", 60),
    KLOPS_MINER("klops miner", 60),
    HEDERA("hedera", 150),
    QUEST_MASTER("quest master", 0),

    // === LIVESTOCK & DOMESTIC ===
    BISON_CALF("bison calf", 50),
    BISON("bison", 90),
    CAMEL_CALF("camel calf", 50),
    CAMEL("camel", 90),
    HORSE_FOAL("horse foal", 30),
    HORSE("horse", 80),
    COW_CALF("cow calf", 30),
    COW_BASE("cow", 70),
    PIG_WILD_PIGLET("pig wild piglet", 20),
    PIG_WILD("pig wild", 50),
    PIG_PIGLET("pig piglet", 15),
    PIG_BASE("pig", 30),
    BOAR_PIGLET("boar piglet", 20),
    BOAR("boar", 60),
    SHEEP_LAMB("sheep lamb", 20),
    SHEEP_BASE("sheep", 50),
    RAM_LAMB("ram lamb", 40),
    RAM("ram", 80),
    MOUFLON_LAMB("mouflon lamb", 30),
    MOUFLON("mouflon", 60),
    GOAT_KID("goat kid", 25),
    GOAT("goat", 60),
    WARTHOG_PIGLET("warthog piglet", 50),
    WARTHOG("warthog", 70),
    ANTELOPE("antelope", 60),
    DEER_STAG("deer stag", 70),
    DEER_DOE("deer doe", 50),
    TURKEY_CHICK("turkey chick", 10),
    TURKEY("turkey", 30),
    SKRILL_CHICK("skrill chick", 10),
    SKRILL("skrill", 20),

    // === AVIANS & SMALL ===
    PTERODACTYL("pterodactyl", 50),
    ARCHAEOPTERYX("archaeopteryx", 40),
    VULTURE("vulture", 40),
    HAWK("hawk", 30),
    OWL_SNOW("owl snow", 25),
    OWL_BROWN("owl brown", 25),
    RAVEN("raven", 30),
    CROW("crow", 15),
    PARROT("parrot", 20),
    FLAMINGO("flamingo", 35),
    PENGUIN("penguin", 25),
    DUCK("duck", 15),
    CHICKEN_DESERT_CHICK("chicken desert chick", 5),
    CHICKEN_DESERT("chicken desert", 20),
    CHICKEN_CHICK("chicken chick", 5),
    CHICKEN_BASE("chicken", 15),
    BLUEBIRD("bluebird", 10),
    FINCH_GREEN("finch green", 10),
    SPARROW("sparrow", 10),
    PIGEON("pigeon", 10),
    WOODPECKER("woodpecker", 10),

    // === AQUATIC ===
    SHARK_HAMMERHEAD("shark hammerhead", 1000),
    JELLYFISH_MAN_OF_WAR("jellyfish man of war", 60),
    JELLYFISH_BLUE("jellyfish blue", 30),
    JELLYFISH_CYAN("jellyfish cyan", 30),
    JELLYFISH_GREEN("jellyfish green", 30),
    JELLYFISH_RED("jellyfish red", 30),
    JELLYFISH_YELLOW("jellyfish yellow", 30),
    EEL_MORAY("eel moray", 60),
    SNAPJAW("snapjaw", 60),
    TRILOBITE_BLACK("trilobite black", 50),
    TRILOBITE("trilobite", 50),
    PIKE("pike", 30),
    SALMON("salmon", 20),
    TROUT_RAINBOW("trout rainbow", 20),
    CATFISH("catfish", 20),
    BLUEGILL("bluegill", 20),
    FROSTGILL("frostgill", 50),
    PIRANHA_BLACK("piranha black", 30),
    PIRANHA("piranha", 25),
    PUFFERFISH("pufferfish", 25),
    CLOWNFISH("clownfish", 15),
    TANG_BLUE("tang blue", 15),
    TANG_CHEVRON("tang chevron", 15),
    TANG_LEMON_PEEL("tang lemon peel", 15),
    TANG_SAILFIN("tang sailfin", 15),
    LOBSTER("lobster", 40),
    CRAB("crab", 30),
    SHELLFISH_LAVA("shellfish lava", 20),
    MINNOW("minnow", 5),

    // === CRITTERS ===
    FROG_BLUE("frog blue", 5),
    FROG_GREEN("frog green", 5),
    FROG_ORANGE("frog orange", 5),
    GECKO("gecko", 10),
    ARMADILLO("armadillo", 60),
    MEERKAT("meerkat", 20),
    SQUIRREL("squirrel", 10),
    MOUSE("mouse", 5),
    BAT_ICE("bat ice", 20),
    BAT("bat", 10),
    HATWORM("hatworm", 15),

    DEFAULT("default", 10);

    private final String keyword;
    private final int xp;

    MobXP(String keyword, int xp) {
        this.keyword = keyword;
        this.xp = xp;
    }

    public String getKeyword() { return keyword; }
    public int getXp() { return xp; }

    public static int getXpForId(String typeId) {
        String cleanId = typeId.replace("_", " ").toLowerCase();

        for (MobXP mob : values()) {
            if (mob != DEFAULT && cleanId.contains(mob.getKeyword())) {
                return mob.getXp();
            }
        }
        return DEFAULT.getXp();
    }
}